version: '3.5'

services:
  keycloak:
    container_name: keycloak_container
    image: bitnami/keycloak:21.0.2
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: ${KEYCLOAK_ADMIN_DEFAULT:-true}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}        
      KEYCLOAK_DATABASE_HOST: ${KEYCLOAK_DATABASE_HOST:-postgres}   
      KEYCLOAK_DATABASE_PORT: ${KEYCLOAK_DATABASE_PORT:-5432}
      KEYCLOAK_DATABASE_NAME: ${KEYCLOAK_DATABASE_NAME:-spring_security}
      KEYCLOAK_DATABASE_USER: ${KEYCLOAK_DATABASE_USER:-user}
      KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD:-root}
      KEYCLOAK_DATABASE_SCHEMA: ${KEYCLOAK_DATABASE_SCHEMA:-public}
      KEYCLOAK_JGROUPS_DISCOVERY_PROTOCOL: ${KEYCLOAK_JGROUPS_DISCOVERY_PROTOCOL:-JDBC_PING}
    volumes:
      - mynewtheme:/opt/bitnami/keycloak/themes/mynewtheme
    ports:
      - "8082:8080"
    networks:
      - util_postgres
    restart: unless-stopped

networks:
  util_postgres: #le rnom du seau existant
    external: true #le rseau existe déja

volumes:
  mynewtheme:  