version: '3'

services:
  db:
    image: mysql:8.0.31
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      #MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
volumes:
  dbdata: